add Leak Detector
sblibs/pySwitchbot pull request #262
Opened 2024-10-30 11:42 UTC by luc-ass

Hi @Danielhiversen,

I have added the new [Leak Detector](https://eu.switch-bot.com/products/switchbot-water-leak-detector) to pySwitchbot. From what I can see this should work but I am not quite sure on how to robustly test, whether all works as expected. It would be great, if you could point me in the right direction.

Thanks,
Lucas

2024-11-17 11:28 UTC, bdraco commented on switchbot/adv_parsers/leak.py
> +    water_leak_detected = None
Please add tests for this parser

2024-11-17 11:29 UTC, bdraco commented
If you run 
`pre-commit install` 
`pre-commit run --all-files`

It should fix the lint issues for you

2024-11-18 19:36 UTC, bdraco requested changes
Please add tests for this parser

2024-12-17 00:02 UTC, bdraco commented on tests/test_adv_parser.py
> +    )
Please add a test for passive scans as well.  In passive mode, the service_data will be empty

2024-12-17 00:03 UTC, bdraco commented
> Hi @bdraco thank you for your input! This addition still needs to be tested with my hardware. Have you got a process how to check which response corresponds to which state? I am not super expericened with hardware testing ☺️

Try to get the device to end up in all possible states and write tests to each state to assert that the data reflects the state you believe the device to be in.  When there aren't docs its usually hours of trial and error to get it as close to correct as possible.

2024-12-17 19:25 UTC, luc-ass commented
> Try to get the device to end up in all possible states and write tests to each state to assert that the data reflects the state you believe the device to be in. When there aren't docs its usually hours of trial and error to get it as close to correct as possible.

I have now acquired data for leak/no leak and different battery levels. I have no idea how to "tamper" with the device, but that kind of message is supported [here](https://github.com/OpenWonderLabs/node-switchbot/blob/latest/src/device/woleak.ts), so I implemented. For now I was able to test with a battery at 9% but still no low_battery bit, while the app already shows it. Looks like it is not really used.

2024-12-17 19:35 UTC, bdraco commented on switchbot/adv_parsers/leak.py
> +        return {}
Please add coverage for this branch

2024-12-17 19:36 UTC, bdraco commented on switchbot/devices/leak.py
> +from __future__ import annotations
We can drop this file since there is no active connection

2024-12-20 19:37 UTC, bdraco approved these changes

2024-12-20 19:37 UTC, merged

2024-12-20 19:37 UTC, bdraco commented
Thanks @luc-ass